# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Broadsage

name: 'End-of-life (EOL) GitHub Action'
description: 'Identifies the End-of-life (EOL) dates for products.'
author: 'Broadsage'

inputs:
  products:
    description: 'Comma-separated list of products to track (e.g., "python,nodejs,ubuntu"). Use "all" to fetch all products.'
    required: true
  
  cycles:
    description: 'JSON object mapping products to specific cycles to track (e.g., {"python": ["3.11", "3.12"], "nodejs": ["20", "21"]}). Leave empty to track all cycles.'
    required: false
    default: '{}'
  
  check-eol:
    description: 'Check if any tracked versions are end-of-life'
    required: false
    default: 'true'
  
  eol-threshold-days:
    description: 'Number of days before EOL to trigger warning (default: 90)'
    required: false
    default: '90'
  
  fail-on-eol:
    description: 'Fail the action if any version is end-of-life'
    required: false
    default: 'false'
  
  fail-on-approaching-eol:
    description: 'Fail the action if any version is approaching EOL within threshold'
    required: false
    default: 'false'
  
  fail-on-stale:
    description: 'Fail the action if any version has not received updates within staleness threshold'
    required: false
    default: 'false'
  
  staleness-threshold-days:
    description: 'Number of days since last release to consider a version stale (default: 365)'
    required: false
    default: '365'
  
  include-discontinued:
    description: 'Include discontinued products/devices in the analysis (e.g., hardware EOL)'
    required: false
    default: 'true'
  
  output-format:
    description: 'Output format: json, markdown, or summary (GitHub Step Summary)'
    required: false
    default: 'summary'
  
  output-file:
    description: 'Path to write output file (optional, in addition to step outputs)'
    required: false
    default: ''
  
  cache-ttl:
    description: 'Cache TTL in seconds for API responses (default: 3600 = 1 hour)'
    required: false
    default: '3600'
  
  github-token:
    description: 'GitHub token for creating issues/PRs (optional, for advanced features)'
    required: false
    default: ''
  
  create-issue-on-eol:
    description: 'Create a GitHub issue when EOL is detected (requires github-token)'
    required: false
    default: 'false'
  
  issue-labels:
    description: 'Comma-separated labels for created issues'
    required: false
    default: 'dependencies,eol,security'
  
  include-latest-version:
    description: 'Include latest version information in output'
    required: false
    default: 'true'
  
  include-support-info:
    description: 'Include support status information in output'
    required: false
    default: 'true'
  
  custom-api-url:
    description: 'Custom API URL (for testing or self-hosted instances)'
    required: false
    default: 'https://endoflife.date/api/v1'
  
  file-path:
    description: 'Path to file containing version information (e.g., helm/values.yaml, package.json)'
    required: false
    default: ''
  
  file-key:
    description: 'Nested key path for YAML/JSON extraction (e.g., "image.tag", "dependencies.python")'
    required: false
    default: ''
  
  file-format:
    description: 'File format for extraction: yaml, json, or text'
    required: false
    default: 'yaml'
  
  version-regex:
    description: 'Regular expression to extract version from any file (e.g., "v([0-9]+\.[0-9]+\.[0-9]+)")'
    required: false
    default: ''
  
  version:
    description: 'Manually specify version (alternative to file extraction). If provided, skips file extraction.'
    required: false
    default: ''
  
  # SBOM Integration
  sbom-file:
    description: 'Path to SBOM file (Software Bill of Materials) in CycloneDX or SPDX format'
    required: false
    default: ''
  
  sbom-format:
    description: 'SBOM format: cyclonedx, spdx, or auto (auto-detect)'
    required: false
    default: 'auto'
  
  sbom-component-mapping:
    description: 'Custom JSON mapping of SBOM component names to endoflife.date product names (e.g., {"my-python": "python"})'
    required: false
    default: ''
  
  semantic-version-fallback:
    description: 'Enable semantic version fallback matching (1.2.3 → 1.2 → 1)'
    required: false
    default: 'true'
  
  # Performance
  api-concurrency:
    description: 'Maximum number of concurrent API requests (1-10, default: 5)'
    required: false
    default: '5'
  
  output-matrix:
    description: 'Enable matrix output generation for GitHub Actions matrix strategies'
    required: false
    default: 'false'
  
  exclude-eol-from-matrix:
    description: 'Exclude end-of-life versions from matrix output'
    required: false
    default: 'true'
  
  exclude-approaching-eol-from-matrix:
    description: 'Exclude versions approaching EOL from matrix output'
    required: false
    default: 'false'
  
  min-release-date:
    description: 'Minimum release date filter (YYYY-MM-DD, YYYY, or >=YYYY)'
    required: false
    default: ''
  
  max-release-date:
    description: 'Maximum release date filter (YYYY-MM-DD, YYYY, or <=YYYY)'
    required: false
    default: ''
  
  max-versions:
    description: 'Maximum number of versions to check per product'
    required: false
    default: ''
  
  version-sort-order:
    description: 'Sort order for versions: newest-first or oldest-first'
    required: false
    default: 'newest-first'
  
  filter-by-category:
    description: 'Filter products by category (e.g., "os", "lang", "db"). Use API endpoint /categories to see available categories.'
    required: false
    default: ''
  
  filter-by-tag:
    description: 'Filter products by tag (e.g., "linux", "microsoft"). Use API endpoint /tags to see available tags.'
    required: false
    default: ''
  
  # Notification Settings
  enable-notifications:
    description: 'Enable notifications (auto-enabled if any webhook URL is provided)'
    required: false
    default: 'false'
  
  slack-webhook-url:
    description: 'Slack webhook URL for EOL notifications'
    required: false
    default: ''
  
  discord-webhook-url:
    description: 'Discord webhook URL for EOL notifications'
    required: false
    default: ''
  
  teams-webhook-url:
    description: 'Microsoft Teams webhook URL for EOL notifications'
    required: false
    default: ''
  
  google-chat-webhook-url:
    description: 'Google Chat webhook URL for EOL notifications'
    required: false
    default: ''
  
  custom-webhook-url:
    description: 'Custom webhook URL for EOL notifications (receives JSON payload)'
    required: false
    default: ''
  
  custom-webhook-headers:
    description: 'Custom headers for webhook (JSON format, e.g., {"Authorization": "Bearer token"})'
    required: false
    default: ''
  
  notify-on-eol-only:
    description: 'Only send notifications when EOL is detected (not for approaching EOL)'
    required: false
    default: 'false'
  
  notify-on-approaching-eol:
    description: 'Send notifications for versions approaching EOL'
    required: false
    default: 'true'
  
  notification-threshold-days:
    description: 'Days before EOL to trigger notifications (separate from fail threshold)'
    required: false
    default: '90'
  
  notification-min-severity:
    description: 'Minimum severity for notifications: info, warning, error, critical'
    required: false
    default: 'info'
  
  notification-retry-attempts:
    description: 'Number of retry attempts for failed notifications'
    required: false
    default: '3'
  
  notification-retry-delay-ms:
    description: 'Delay in milliseconds between notification retries'
    required: false
    default: '1000'

outputs:
  eol-detected:
    description: 'Boolean indicating if any EOL versions were detected'
  
  version:
    description: 'Extracted version from file (if file-path was provided)'
  
  approaching-eol:
    description: 'Boolean indicating if any versions are approaching EOL'
  
  results:
    description: 'JSON string containing all version information'
  
  eol-products:
    description: 'JSON array of products that are end-of-life'
  
  approaching-eol-products:
    description: 'JSON array of products approaching end-of-life'
  
  latest-versions:
    description: 'JSON object mapping products to their latest versions'
  
  summary:
    description: 'Human-readable summary of findings'
  
  total-products-checked:
    description: 'Total number of products checked'
  
  total-cycles-checked:
    description: 'Total number of cycles checked'
  
  matrix:
    description: 'JSON matrix for GitHub Actions (format: { "versions": [...] })'
  
  matrix-include:
    description: 'Detailed JSON matrix with metadata (format: { "include": [...] })'
  
  stale-detected:
    description: 'Boolean indicating if any stale versions were detected (no recent releases)'
  
  stale-products:
    description: 'JSON array of products with stale versions (no recent updates)'
  
  discontinued-detected:
    description: 'Boolean indicating if any discontinued products were detected'
  
  discontinued-products:
    description: 'JSON array of discontinued products/devices'
  
  extended-support-products:
    description: 'JSON array of products with extended support available'


runs:
  using: 'node24'
  main: 'dist/index.js'
