# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 BroadSage

name: Docker Image EOL Monitoring

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check-base-images:
    name: Monitor Docker Base Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check base image EOL status
        id: eol-check
        uses: broadsage/endoflife-action@v1
        with:
          # Track base images and runtimes
          products: 'ubuntu,alpine,debian,python,nodejs,nginx'
          
          # Specify exact versions used in Dockerfiles
          cycles: |
            {
              "ubuntu": ["22.04", "20.04"],
              "alpine": ["3.19", "3.18"],
              "python": ["3.11", "3.12"],
              "nodejs": ["20"],
              "nginx": ["1.25"]
            }
          
          # Alert 180 days before EOL for planning
          eol-threshold-days: 180
          
          # Create issues for tracking
          create-issue-on-eol: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-labels: 'docker,dependencies,eol,security'
          
          # Generate markdown report
          output-format: 'markdown'
          output-file: 'docker-eol-report.md'
          
          # Fail on EOL to prevent using unsupported images
          fail-on-eol: true
          fail-on-approaching-eol: false
      
      - name: Upload EOL report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-eol-report
          path: docker-eol-report.md
          retention-days: 30
      
      - name: Comment on PR if EOL detected
        if: github.event_name == 'pull_request' && steps.eol-check.outputs.eol-detected == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('docker-eol-report.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ⚠️ Docker Base Image EOL Warning\n\n${report}`
            });
